version: 1
build:
  binary: hobbyd
accounts:
- name: validator1
  coins:
  - 400000000000000000000000uhby
  - 400000000000000000000000usby
- name: validator2
  coins:
  - 400000000000000000000000uhby
  - 400000000000000000000000usby
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: validator1
  bonded: 200000000000000000000000uhby
  home: "$HOME/.hobby"
  app:
     minimum-gas-prices: "10000000usby,10000000uhby"
     api:
         enable: true
         enabled-unsafe-cors: true
         address: "tcp://0.0.0.0:1317"
     grpc:
         enable: true
         address: "0.0.0.0:9090"
     grpc-web:
         address: "0.0.0.0:9091"
         enable: true
         enable-unsafe-cors: true
     json-rpc:
         enable: true
         address: "0.0.0.0:8545"
         ws-address: "0.0.0.0:8546"
  config:
     consensus:
         timeout_commit: "7s"
     proxy_app: "tcp://0.0.0.0:26658"
     moniker: "node0"
     rpc:
         max_body_bytes: "10240000"
         laddr: "tcp://0.0.0.0:26657"
     p2p:
         laddr: "tcp://0.0.0.0:26656"
         persistent_peers: ""
         allow_duplicate_ip: true
     instrumentation:
         prometheus: true
         prometheus_listen_addr: ":26660"
genesis:
  chain_id: "hobby_9001-1"
  initial_height: "1"
  genesis_time: "2023-11-09T07:46:56.293077949Z"
  consensus_params:
    block:
      max_gas: "1000000000"
    version:
      app: "9160"
  app_state:
    evm:
      params:
        evm_denom: "usby"
    claims:
      params:
        claims_denom: "usby"
    feemarket:
      params:
        base_fee: "5000000"
        min_gas_price: "10000000"
        base_fee_change_denominator: 8
        elasticity_multiplier: 2
        enable_height: 0
        min_gas_multiplier: "0.500000000000000000"
        no_base_fee: false
    hobby:
      params:
        exchange:
          from_denom: "uhby"
          to_denom: "usby"
          exchange_ratio: "10.0"
          allow_list: [ ]
    bank:
      denom_metadata:
        - description: "The native staking token"
          base: "uhby"
          display: "hby"
          name: "staking token"
          symbol: "HBY"
          denom_units:
            - aliases: [ ]
              denom: "uhby"
              exponent: 0
            - aliases: [ ]
              denom: "ahby"
              exponent: 9
            - aliases: [ ]
              denom: "hby"
              exponent: 18
        - description: "The native gov token"
          base: "usby"
          display: "sby"
          name: "mint token"
          symbol: "SBY"
          denom_units:
            - aliases: [ ]
              denom: "usby"
              exponent: 0
            - aliases: [ ]
              denom: "asby"
              exponent: 9
            - aliases: [ ]
              denom: "sby"
              exponent: 18
    staking:
      params:
        bond_denom: "uhby"
        max_validators: "500"
        min_bond_amount: "1000000000000000000000"
        max_bond_amount: "300000000000000000000000"
        enable_evm: true
        min_commission_rate: "0.0"
        unbonding_time: "60s"
    mint:
      minter:
        annual_provisions: "0.000000000000000000"
        inflation: "0.000000000000000000"
      params:
        mint_denom: "usby"
        blocks_per_year: "4505142"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.200000000000000000"
        inflation_min: "0.070000000000000000"
        inflation_rate_change: "0.130000000000000000"
        reduction:
          enable: true
          total_provisions: "500000000000000000000000000"
          heights: [ 9010284, 18020568, 27030852, 36041136, 45051420 ]
    gov:
      params:
        gov_erc721:
          allow_deploy: true
          master_vesting_epochs: "100"
          slave_vesting_epochs: "100"
          common_vesting_epochs: "100"
          settle_interval_epochs: "10"
          contract_admin_addr: "0x90cfd4d61c9d4c63f2e4648229775aba19ced8df"
        min_deposit:
          - amount: "10000000000000000000000"
            denom: "usby"
    distribution:
      params:
        base_proposer_reward: "0.010000000000000000"
        bonus_proposer_reward: "0.040000000000000000"
        community_tax: "0.000000000000000000"
        withdraw_addr_enabled: true
    crisis:
      constant_fee:
        amount: "10000000000000000000"
        denom: "usby"
